handling_symlinks

diff --git a/misc/create_bashenv/conda_activate b/misc/create_bashenv/conda_activate
--- a/misc/create_bashenv/conda_activate
+++ b/misc/create_bashenv/conda_activate
@@ -1,24 +1,18 @@
 # (_CONDA_ROOT inserted by installer)
-here="$(unset CDPATH && cd "$(dirname "${BASH_SOURCE[0]}")/../" && echo $PWD)"
+here="`dirname "${BASH_SOURCE[0]}"`"
+[[ $here != /* ]] && here="`echo $PWD`/$here"
 
 relocate_conda () {
-    test -e "$_CONDA_ROOT" && return 0
+    test -e "$_CONDA_ROOT/bin" && return 0
     echo "Symlinking "$here" -> "$_CONDA_ROOT""
-    ln -s "$here" "$_CONDA_ROOT" || { echo "Sorry. Cannot do that"; return 1; }
+    local cr="$(unset CDPATH && cd "$(dirname "$here")" && cd .. && echo $PWD)"
+    ln -s "$cr" "$_CONDA_ROOT" || { echo "Sorry. Cannot do that"; return 1; }
 }
 
-if_relocated () { test "${here:-}x" != "${_CONDA_ROOT:-}x"; }
+if_relocated () { test "${here:-}x" != "${_CONDA_ROOT:-}/binx"; }
 
 activate_relocated_conda () {
     source "${_CONDA_ROOT}/bin/activate"
-}
-
-activate_conda () {
-    test "${here:-}x" != "${_CONDA_ROOT:-}x" && {
-        echo "Using Conda in "$_CONDA_ROOT"" >&2
-        source "$_CONDA_ROOT/bin/activate"
-        return $?
-    }
 }
 
 activate_conda () {
