added exits when tests fail

diff --git a/misc/create_bashenv/create b/misc/create_bashenv/create
--- a/misc/create_bashenv/create
+++ b/misc/create_bashenv/create
@@ -162,7 +162,7 @@ activate_conda () {
 
 add_base_packages () {
     echo "Adding base package $base_packages"
-    conda install -y $base_packages
+    conda install -y $base_packages || die "conda install of $base_packages failed"
 }
 
 clean_conda () {
@@ -213,14 +213,14 @@ test_success () {
         line="`echo "$line" | xargs`"
         test "${line:-}x" == "x" && continue
         nfo "testing: $line"
-        $line
+        $line || die "$line failed"
     done <<< "${tests:-}"
 
     while read -r line; do
         line="`echo "$line" | xargs`"
         test "${line:-}x" == "x" && continue
         nfo "testing: python -c $line"
-        eval "python -c \"$line\""
+        eval "python -c \"$line\"" || die "Failed:\n$line\n"
     done <<< "${tests_python:-}"
 
 }
