relocation

diff --git a/misc/create_bashenv/create b/misc/create_bashenv/create
--- a/misc/create_bashenv/create
+++ b/misc/create_bashenv/create
@@ -18,7 +18,7 @@ base_packages="git constructor"
 dvcs=git
 HOME="${HOME:-/root}"
 be_config_file=
-
+userid=
 # filename which sets sys.path, which we will turn into PYTHONPATH:
 # e.g. a buildout result:
 local_pypath_from_sys_path_in=
@@ -30,7 +30,7 @@ cached_installer="/tmp/miniconda<conda_ver>-<arch>.sh"
 HOME="${HOME:-/root}"
 conda_ver="3-latest"
 arch="Linux-x86_64"
-root_python=
+conda_rootenv_python=
 usage="Creates Bashenv Repos From Scratch
 
 By default it commits all files into a DVCS so that you can push the complete
@@ -39,29 +39,39 @@ environment to a server - plus see all changes after usage.
 Usage: $me [OPTIONS] go
 
 Options:
--b: Bootstrap. We create a bashenv from scratch, i.e. not a new one from within
+-a: Arch of conda to use, e.g. 'Linux-x86_64' [default: $arch]
+-b: Bootstrap mode. We create a bashenv from scratch, i.e. not a new one from within
     an existing install with same prefix.
 -c: Read config file [default from any activated bashenv's prefix/be_config file
     Samples in misc/be_configs
--V: Version of conda to use [default: $conda_ver]
--a: Arch of conda to use, e.g. 'Linux-x86_64' [default: $arch]
--C: Use this conda installer file [default: $cached_installer]
--G: Create new .$dvcs repo (requires -D if one exists)
--D: Remove any existing repo before creation of new one
 -d: DVCS to use (git or hg) [default: $dvcs]
--P: Push updates back to master
+-g: If you point to a remote repo, you need git/hg already when running this -
+we do not download this as zip, just in order to create this ;-)
+-h: Show help
+-i: Should we install another python into the root env e.g. via conda install python=3.6
 -p: Set bashenv(conda) prefix [default: $conda_prefix].
     This is the directory we will install everything into.
     If we are within another prefix this sets -b (bootstrap mode).
+-u: Set remote repo user (e.g. github account name)
+-x: Set -x (trace mode for debugging)
 -A: Auto activate, via $HOME/.bashrc.
--N: Do NOT touch bashrc (not even to register the activation function)
+-C: Use this conda installer file [default: $cached_installer]
+-D: Remove any existing repo before creation of new one
 -F: Write register function into different file than $HOME/.bashrc
--i: Should we install another python into the root env e.g. via conda install python=3.6
+-G: Create new .$dvcs repo (requires -D if one exists)
+-N: Do NOT touch bashrc (not even to register the activation function)
+-P: Push updates back to master
+-V: Version of conda to use [default: $conda_ver]
 
 Notes:
--i: Leave empty to use the python in the installer (-V) else say e.g. -i 3.6
 -a: See https://repo.continuum.io/miniconda/ regarding what is available for
     Linux-x86_64
+
+-i: Leave empty to use the python in the installer (-V) else say e.g. -i 3.6
+
+-u: For github remote, if not set we check also \`git config github.user\`
+    set via \`'git config --global github.user defunkt\`
+
 -A: By default we just add a function ('be_<your prefix>') to activate on demand
 to your .bashrc.
 
@@ -72,15 +82,17 @@ to your .bashrc.
     - No entry into \$be_bashenvs_known
     If you supply a different file via -F then -N has no effect.
 
--g: If you point to a remote repo, you need git/hg already when running this -
-we do not download this as zip, just in order to create this ;-)
-
 Actions:
+go:
 - Downloads initial conda if not present in $here
 - Then runs the flow in main, ending in a git repo.
 
 Example:
 $me -rpg https://github.com/axiros/bashenv_kickstart go
+
+repo_push:
+- Only creates remote repo if not existing then pushes this bashenv up
+
 "
 
 # reminder: -e fails script also if last statement of a function is false
@@ -102,11 +114,12 @@ do_touch_bashrc=true
 
 
 # -------------------------------------------------------------------- internal
-_opts="PDc:C:NF:AGd:bp:g:xhV:a:i:"
+_opts="a:bc:d:g:hi:p:u:xAC:DF:GNPV:"
 _take_bashenv_from_conda_prefix=
 # fix. always:
 _bin_app_env_bash="/bin/app/environ/bash"
 _fn_default_readme="$here/README_default.md"
+_fn_conda_activate="$here/conda_activate"
 # -----------------------------------------------------------------------------
 
 source_functions () {
@@ -120,29 +133,29 @@ parse_cli () {
     OPTIND=
     while getopts "$_opts" opt; do
         case "$opt" in
-            i) root_python="$OPTARG";;
-            d) dvcs="$OPTARG";;
-            c) be_config_file_orig="$OPTARG";; # read already for config defaults
-            h) exit_sh_help;;
-            A) auto_activate_via_bashrc=true;;
-            N) do_touch_bashrc=false;;
-            b) bootstrap_mode=true;;
-            G) create_new_repo=true;;
-            D) remove_existing_repo=true;;
-            p) conda_prefix="$OPTARG";;
-            C) cached_installer="$OPTARG";;
-            P) push_back=true;;
-            F) fn_register_file="$OPTARG";;
-            V) conda_ver="$OPTARG";;
             a) arch="$OPTARG";;
+            b) bootstrap_mode=true;;
+            c) be_config_file_orig="$OPTARG";; # read already for config defaults
+            d) dvcs="$OPTARG";;
             g) repo_to_update_dir_or_url="$OPTARG";;
+            h) exit_sh_help;;
+            i) conda_rootenv_python="$OPTARG";;
+            p) conda_prefix="$OPTARG";;
+            u) userid="$OPTARG";;
             x) set -x;;
+            A) auto_activate_via_bashrc=true;;
+            C) cached_installer="$OPTARG";;
+            D) remove_existing_repo=true;;
+            F) fn_register_file="$OPTARG";;
+            G) create_new_repo=true;;
+            N) do_touch_bashrc=false;;
+            P) push_back=true;;
+            V) conda_ver="$OPTARG";;
             *) exit_sh_help 1
         esac
     done
     shift $((OPTIND-1))
     run_cmd="${1:-}"
-    test "${run_cmd:-}x" != "gox" && exit_sh_help 1 || return 0
 }
 
 conda_download_url () {
@@ -188,7 +201,7 @@ check_local_paths_present () {
 check_enforce_repo_switches () {
     # Currently we do not support inplace updates so this is actually
     # not needed. But we leave it for later.
-    test "${create_new_repo:-}x" == "xtrue"  || {
+    test "${create_new_repo:-}x" == "truex"  || {
         $push_back && {
             die "-G (repo create) not set, cannot push back a not existing repo"
         }
@@ -203,7 +216,7 @@ check_enforce_repo_switches () {
     del "$conda_prefix/.$dvcs"
 }
 
-do_bootstrap_remove_existing () {
+do_bootstrap_stop_if_existing () {
     test -e "$conda_prefix" || {
         echo "None found at $conda_prefix"
         return 0
@@ -259,10 +272,14 @@ activate_conda () {
     test "$exe" == "$conda_prefix/bin/python" || \
         die "activation error - expected $conda_prefix/bin/python - got $exe"
 }
-install_other_root_python (){
-    test "${root_python:-}x" == "x" && { nfo "no other root python"; return 0; }
-    nfo "conda install python=="$root_python""
-    conda install -y python=="$root_python" || die "failed"
+
+install_other_conda_rootenv_python (){
+    test "${conda_rootenv_python:-}x" == "x" && {
+        nfo "no other root python required"
+        return 0
+    }
+    nfo "conda install python=="$conda_rootenv_python""
+    conda install -y python=="$conda_rootenv_python" || die "failed"
 }
 
 add_base_packages () {
@@ -294,7 +311,7 @@ cd_conda () {
     cd "$conda_prefix"
 }
 
-create_dvcs_repo () {
+create_or_update_dvcs_repo () {
 
     $create_new_repo || {
         nfo "-G not set -> no action"
@@ -316,26 +333,78 @@ create_dvcs_repo () {
     $dvcs status
     is_hg && hg -q addrem
     is_hg || git add -A
-    $dvcs commit -qam 'by create' || true
+    $dvcs commit -am 'by bashenv' || true
     return 0
 }
 
+create_remote_repo () {
+    local repo_name="`act_func_name`"
+    set -x
+    local user="${userid:-$(git config github.user)}"
+    set +x
+    local url="https://api.github.com/user/repos"
+    echo
+    nfo "Reponame: $repo_name@$url"
+    test "${user:-}x" == "x" && {
+        read -p "User for $url: " user
+    }
+    nfo "Will push as $user to $url"
+    read -sp 'Password: ' password
+    python -c 'if 1:
+    import requests, json
+    m = {"name": "'$repo_name'",
+         "description": "test",
+         "private": False,
+         "has_issues": True,
+         "has_wiki": False,
+         "has_downloads": True
+     }
 
-do_push_up_to_master () {
-    $push_back || { nfo "-P not set -> not pushing back"; return 0; }
-    $dvcs push
+    res = requests.post("'$url'",
+        data=json.dumps(m),
+        auth=("'$user'", "'$password'"))
+
+    print(json.loads(res.text)["git_url"])
+    ' || die "repo creation failed"
+    set -x
+    git remote add origin "git@github.com:$user/$repo_name.git"
 }
 
-create_act_func_name () {
+
+do_create_master_repo_or_update_existing () {
+    # we allow to call this function anytime, not only at create but also
+    # when activated later:
+    test "${conda_prefix:-}x" == "x" && conda_prefix="$CONDA_PREFIX"
+    test "${conda_prefix:-}x" == "x" && die "No conda prefix"
+    test -e "$conda_prefix/bin" || die "No bin dir"
+
+    cd "$conda_prefix"
+
+    create_or_update_dvcs_repo
+    $push_back || { nfo "-P not set -> not pushing back"; return 0; }
+
+    is_hg && { sh hg push; return 0; }
+
+    test "`git remote show`x" == "x" && create_remote_repo
+
+    git push -u origin master
+}
+
+
+act_func_name () {
     # getting a function name which bash accepts:
-    act_func_name="`python -sSc "if 1:
+    echo "`python -sSc "if 1:
     import string
     C = string.digits + string.ascii_letters + '_'
     p, f = '$conda_prefix'.rsplit('/', 1)
+    # a tmp package should look like normal, ugly tmp removal:
+    # we assume there are no collisions with a / installed one:
+    if p.startswith('/tmp'):
+        p = p[4:]
     clean = lambda s: ''.join([c for c in s if c in C])
     f, p = (clean(f), clean(p.replace('/', '_')))
-    print('be_%s%s' % (f, p))
-    " ` "
+    print(('be_%s%s' % (f, p)).strip())
+    "`"
 }
 
 
@@ -446,7 +515,7 @@ do_add_activate_to_bashrc () {
     # positional args evaluated there:
     local marker='"'$conda_prefix'/bin/app/environ/bash/be_active"'
     marker="$marker $auto_activate_via_bashrc"
-    marker="$marker $act_func_name"
+    marker="$marker `act_func_name`"
 
     activation_cmd='source '$marker''
     nfo "Adding to $fn: $activation_cmd"
@@ -566,6 +635,21 @@ write_be_config () {
     echo >> "$c"
 }
 
+adapt_conda_activate () {
+    # are we already placed correctly, e.g. after git checkout when activate
+    # is sourced from outside conda
+    echo "#!/usr/bin/env sh"               > "$conda_prefix/bin/activate"
+    echo "_CONDA_ROOT=\"$conda_prefix\""  >> "$conda_prefix/bin/activate"
+    cat "$_fn_conda_activate"             >> "$conda_prefix/bin/activate"
+}
+
+write_bash () {
+    local b="$conda_prefix/bin/bash"
+    echo "#!/usr/bin/env sh" > "$b"
+    echo "# Allowing aliases, prompt etc w/o modifying user's bashrc" >> "$b"
+    echo 'source "'$conda_prefix'/bin/app/environ/bash/bashrc"' >> "$b"
+    echo '/bin/bash $*' >>"$b"
+}
 
 show_info () {
     echo "Init conda installed."
@@ -587,42 +671,51 @@ main () {
     sh do_check_if_located_within_existing_install || true
     sh source_configfile $*
     parse_cli $* || exit_sh_help
-    sh derive_cached_installer_name_by_conda_ver
-    sh derive_target_conda_prefix
-    sh check_local_paths_present
-    sh check_enforce_repo_switches
-    sh do_activate_existing_for_git_hg || true
-    sh do_check_set_bootstrap_mode
-    sh prevent_copy_into_same_dir
-    # sh do_bootstrap_remove_existing
-    # sh fetch_repo_to_update_url || die "Error fetching repo"
-    $bootstrap_mode && {
-        sh do_bootstrap_remove_existing
-        sh get_miniconda
-        sh chmod_conda
-        sh install_conda
+
+    if [ "${run_cmd:-}x" == "repo_pushx" ]; then
+        create_new_repo=true
+        push_back=true
+        sh do_create_master_repo_or_update_existing
+
+    elif [ "${run_cmd:-}x" == "gox" ]; then
+
+        sh derive_cached_installer_name_by_conda_ver
+        sh derive_target_conda_prefix
+        sh check_local_paths_present
+        sh check_enforce_repo_switches
+        sh do_activate_existing_for_git_hg || true
+        sh do_check_set_bootstrap_mode
+        sh prevent_copy_into_same_dir
+        # sh do_bootstrap_stop_if_existing
+        # sh fetch_repo_to_update_url || die "Error fetching repo"
+        $bootstrap_mode && {
+            sh do_bootstrap_stop_if_existing
+            sh get_miniconda
+            sh chmod_conda
+            sh install_conda
+            sh force_utf8
+            sh activate_conda
+            sh install_other_conda_rootenv_python
+            sh add_base_packages
+        }
+        sh mkdir_etc_conda_activate
+        #sh do_fail_on_no_git_hg # hg no more currently
+        sh copy_base_env_over
+        sh add_channels
+        sh add_packages
+        sh add_pips
+        sh add_locals
         sh force_utf8
-        sh activate_conda
-        sh install_other_root_python
-        sh add_base_packages
-    }
-    sh mkdir_etc_conda_activate
-    #sh do_fail_on_no_git_hg # hg no more currently
-    sh copy_base_env_over
-    sh add_channels
-    sh add_packages
-    sh add_pips
-    sh add_locals
-    sh force_utf8
-    sh write_be_config $*
-    sh clean_conda
-    sh cd_conda
-    sh test_success
-    sh create_dvcs_repo
-    sh create_act_func_name
-    sh do_add_activate_to_bashrc
-    sh do_push_up_to_master
-    show_info
+        sh write_be_config $*
+        sh adapt_conda_activate $*
+        sh write_bash
+        sh clean_conda
+        sh cd_conda
+        sh test_success
+        sh do_add_activate_to_bashrc
+        sh do_create_master_repo_or_update_existing
+        show_info
+    fi
 }
 
 # sourced? then return
